#!/usr/bin/env perl

=head1 NAME

salted_hash - Create salted hash from cleartext password

=head1 COPYRIGHT AND DISCLAIMER

(C) 2019 by Heinz Knutzen     <heinz.knutzen@gmail.com>

https://github.com/hknutzen/Netspoc-Web

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

=cut

use strict;
use warnings;
use Digest::SHA qw/sha256_hex/;
use Crypt::SaltedHash;

my $passwd = <>;
chomp $passwd;

# Create salted hash from password.
my $csh = Crypt::SaltedHash->new(algorithm => 'SHA-256');
$csh->add($passwd);
my $hash = $csh->generate;

print "$hash\n";
